config/routes.rb
DemoApp::Application.routes.draw do
  mount Forem::Engine, :at => "/forums"

  devise_for :users, :controller => {:registrations => 'registrations'}

  root :to => 'welcome#index'
  match 'dashboard' => 'welcome#dashboard'

  get "twitter/new"
  get "twitter/callback"
  get "twitter/deactivate"
  post "twitter/post"

  get "facebook/new"
  get "facebook/callback"
  get "facebook/deactivate"
  post "facebook/post"

  get "foursquare/new"
  get "foursquare/callback"
  get "foursquare/deactivate"
  post "foursquare/push"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :authenticate_user!, :except => [:index]
	def index
	end

	def dashboard
		twitter_account = TwitterAccount.find_by_user_id(current_user.id)
		@twitter_not_link = twitter_account.nil? || !twitter_account.active
		@twitter_button_class = @twitter_not_link ? "btn-success" : "btn-danger"		
		@twitter_text = @twitter_not_link ? "Link Twitter" : "Unlink Twitter"		
		@twitter_path = @twitter_not_link ? twitter_new_path : twitter_deactivate_path

		facebook_account = FacebookAccount.find_by_user_id(current_user.id)
		@facebook_not_link = facebook_account.nil? || !facebook_account.active
		@facebook_button_class = @facebook_not_link ? "btn-success" : "btn-danger"
		@facebook_text = @facebook_not_link ? "Link Facebook" : "Unlink Facebook"
		@facebook_path = @facebook_not_link ? facebook_new_path : facebook_deactivate_path

		foursquare_account = FoursquareAccount.find_by_user_id(current_user.id)
		@foursquare_not_link = foursquare_account.nil? || !foursquare_account.active
		@foursquare_button_class = @foursquare_not_link ? "btn-success" : "btn-danger"
		@foursquare_text = @foursquare_not_link ? "Link Foursquare" : "Unlink Foursquare"
		@foursquare_path = @foursquare_not_link ? foursquare_new_path : foursquare_deactivate_path
		if !@foursquare_not_link
			@foursquare_checkins = foursquare_account.foursquare_checkins
		end
	end

	def draw
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/dashboard.html.erb
<% provide :title, "Dashboard" %>
<h1>Dashboard</h1>
<div class="row">
  <div class="span9">
  	<h2>Link your social media accounts in the right tab!</h2>
  	<h2>After that you can post messages from this tab!</h2>
  	<div class="row">
	  	<div class="span3">
	  		<% if !@foursquare_not_link %>
	  			<p>Foursquare checkin logs during subscription</p>
	  			<% @foursquare_checkins.each do |c| %>
	  				<p><%= c.created_at.to_date %>: <%= c.venue_name %></p>
	  			<% end %>
	  		<% end %>
	  	</div>
	  	<div class="span3">
	  		<% if !@twitter_not_link %>
	  			<%= form_tag(twitter_post_path, :method => "post") do %>
	  				<%= label_tag(:post, "Tweet:") %>
					<%= text_field_tag(:post) %>
					<%= image_submit_tag("twitter_128.png", :style => "width:auto;border:0;") %>
	  			<% end %>
	  		<% end %>
	  	</div>
	  	<div class="span3">
	  		<% if !@facebook_not_link %>
	  			<%= form_tag(facebook_post_path, :method => "post") do %>
	  				<%= label_tag(:post, "Post on your wall:") %>
					<%= text_field_tag(:post) %>
					<%= image_submit_tag("facebook_128.png", :style => "width:auto;border:0;") %>
	  			<% end %>
	  		<% end %>
	  	</div>
  	</div>
  </div>

  <div class="span3">
  	<div class="tabbable"> <!-- Only required for left/right tabs -->
	  <ul class="nav nav-tabs">
	    <li class="active"><a href="#tab1" data-toggle="tab">Foursquare</a></li>
	    <li><a href="#tab2" data-toggle="tab">Twitter</a></li>
	    <li><a href="#tab3" data-toggle="tab">Facebook</a></li>
	  </ul>
	  <div class="tab-content">
	    <div class="tab-pane active" id="tab1">
	      <div class="btn-group">
			  <a class="btn <%= @foursquare_button_class %>" href="<%= @foursquare_path %>">
			  	<%= @foursquare_text %>
			  </a>
		  </div>
	    </div>
	    <div class="tab-pane" id="tab2">
	      <div class="btn-group">
			  <a class="btn <%= @twitter_button_class %>" href="<%= @twitter_path %>">
			  	<%= @twitter_text %>
			  </a>
		  </div>
	    </div>
	    <div class="tab-pane" id="tab3">
	      <div class="btn-group">
			  <a class="btn <%= @facebook_button_class %>" href="<%= @facebook_path %>">
			  	<%= @facebook_text %>
			  </a>
		  </div>
	    </div>
	  </div>
	</div>
  </div>

</div>

app/views/welcome/draw.html.erb
<style type="text/css">
	#selectable_source .ui-selecting { background: #89C0E6; }
	#selectable_source .ui-selected.selectedfilter { background: #5BAFE7; color: white; }
	#selectable_source { list-style-type: none; margin: 0; padding: 0; width: 100%; }
	#selectable_source li { margin: 3px; padding: 0.4em; font-size: 1.4em; height: 18px; border: 2px;}
	#selectable_source .correct { background: #5DD3A4; color: black;}
	#selectable_source .wrong { background: #F39814; color: black;}

	#selectable_translation .ui-selecting { background: #89C0E6; }
	#selectable_translation .ui-selected.selectedfilter { background: #5BAFE7; color: white; }
	#selectable_translation { list-style-type: none; margin: 0; padding: 0; width: 100%; }
	#selectable_translation li { margin: 3px; padding: 0.4em; font-size: 1.4em; height: 18px; border: 2px;}
	#selectable_translation .correct { background: #5DD3A4; color: black;}
	#selectable_translation .wrong { background: #F39814; color: black;}

	.source {
		display: none;
	}
	.target {
		display: none;
	}

	#menu {
	    display: none;
	    position: absolute;
	    padding: 10px;
	    background-color: #ddd;
	    border: 1px solid #000;
	}

</style>

<script type="text/javascript">
	$(function() {
		$( "#selectable_source" ).selectable({
			selected: function (event, ui) {
		        if ($(ui.selected).hasClass('selectedfilter')) {
		            $(ui.selected).removeClass('selectedfilter');
		            $(ui.selected).removeClass('ui-selected');
		            // do unselected stuff
		        } else {            
		            $(ui.selected).addClass('selectedfilter');
		            var sourceText = $($(ui.selected).children()[1]).text();
		            var targetText = $($(ui.selected).children()[2]).text();
		            if( sourceText != '' && targetText != '') {
		            	var sourceTokens = sourceText.split(',');
		            	var targetTokens = targetText.split(',');
		            	for (var i = 0; i < sourceTokens.length; ++i) {
		            		$($('#selectable_source').children()[parseInt(sourceTokens[i])]).addClass('ui-selected').addClass('selectedfilter');	
		            	}
		            	for (var i = 0; i < targetTokens.length; ++i) {
		            		$($('#selectable_translation').children()[parseInt(targetTokens[i])]).addClass('ui-selected').addClass('selectedfilter');
		            	};            		
		            }
		            console.log(sourceText);
		            console.log(targetText);
		            // do selected stuff
		        }
		    },
		    unselected: function (event, ui) {
		        $(ui.unselected).removeClass('selectedfilter');
		    }
		});
		$( "#selectable_translation" ).selectable({
			selected: function (event, ui) {
		        if ($(ui.selected).hasClass('selectedfilter')) {
		            $(ui.selected).removeClass('selectedfilter');
		            $(ui.selected).removeClass('ui-selected');
		            // do unselected stuff
		        } else {            
		            $(ui.selected).addClass('selectedfilter');
		            // do selected stuff
		        }
		    },
		    unselected: function (event, ui) {
		        $(ui.unselected).removeClass('selectedfilter');
		    }
		});

		// right click and add tag to each word
		$(".customerRow").contextMenu({ menu: 'menu' }, 
        function(action, el, pos) { 
        	var $el = el;
        	var oldTag = $el[0].lastChild;
        	var newTag = document.createElement("SPAN");
        	var text = document.createTextNode(action);
        	newTag.appendChild(text);
        	$el[0].removeChild(oldTag);
        	$el[0].appendChild(newTag);
        	// console.log(action);
        	// console.log(el);
        	// console.log(pos);
        });
	});

	// Keys "enum"
	var KEY = {
	    BACKSPACE: 8,
	    TAB: 9,
	    ENTER: 13,
	    ESCAPE: 27,
	    SPACE: 32,
	    PAGE_UP: 33,
	    PAGE_DOWN: 34,
	    END: 35,
	    HOME: 36 ,
	    LEFT: 37,
	    UP: 38,
	    RIGHT: 39,
	    DOWN: 40,
	    NUMPAD_ENTER: 108,
	    COMMA: 188,
	    C_SMALL: 99,
	    C_BIG: 67,
	    D_SMALL: 100,
	    D_BIG: 68,
	    I_SMALL: 105,
	    I_BIG: 73,
	};

	var MOUSE = {
		LEFT: 1,
		MIDDLE: 2,
		RIGHT: 3,
	};
</script>

<table>
	<tr>
		<td width="200px">
			<ol id="selectable_source">
				<li class="ui-widget-content customerRow"><span>Item 1</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 2</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 3</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 4</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 5</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 6</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 7</span><span class="source"></span><span class="target"></span><span></span></li>
			</ol>
		</td>
		<td id="canvas" width="200px"></td>
		<td width="200px">
			<ol id="selectable_translation">
				<li class="ui-widget-content customerRow"><span>Item 1</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 2</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 3</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 4</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 5</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 6</span><span class="source"></span><span class="target"></span><span></span></li>
				<li class="ui-widget-content customerRow"><span>Item 7</span><span class="source"></span><span class="target"></span><span></span></li>
			</ol>
		</td>
	</tr>
</table>

<ul id="menu" class="contextMenu">
  	<li><a href="#MET">Meta Word</a></li>        
    <li><a href="#TOK">Tokenization Error</a></li>   
    <li><a href="#TYP">Typo</a></li>                 
    <li><a href="#">Delete Tag</a></li>
</ul>

<script type="text/javascript">
	var canvas = Raphael("canvas");
	var $canvas = $("#canvas");
	var $li;
	var sourceNum = $("#selectable_source").children().length;
	var translationNum = $("#selectable_translation").children().length;
	var lines = new Array(sourceNum); 
	for (var i = lines.length - 1; i >= 0; --i) {
		lines[i] = new Array(translationNum); // translation items number
	}; 
	function drawLines(sources, targets, color) {
		if (sources != [] && targets != []){
			var sourceTokens = new Array();
			var targetTokens = new Array();
			// get sources and targets index
			$.each(sources, function(s_i,s_val){
				var $source = $(s_val);
				sourceTokens.push($source.parent().children().index($source));
			});
			$.each(targets, function(t_i,t_val){
				var $target = $(t_val);
				targetTokens.push($target.parent().children().index($target));
			});

			// add content for source and target span
			$.each(sources,function(s_i,s_val){
				var $source = $(s_val);
				$($source.children()[1]).text(sourceTokens.join());
				$($source.children()[2]).text(targetTokens.join());
			})
			$.each(targets,function(t_i,t_val){
				var $target = $(t_val);
				$($target.children()[1]).text(sourceTokens.join());
				$($target.children()[2]).text(targetTokens.join());
			})		    

			// draw lines
			$.each(sources, function(s_i,s_val){
				var $source = $(s_val);
				var startIndex = $source.parent().children().index($source);
				$.each(targets, function(t_i,t_val){
					var $target = $(t_val);					
					var endIndex = $target.parent().children().index($target);
					if (lines[startIndex][endIndex] == undefined || lines[startIndex][endIndex].attrs == null) {
						drawLine($source, $target, startIndex, endIndex, sourceTokens, targetTokens, color);
					} else {
						lines[startIndex][endIndex].remove();
						drawLine($source, $target, startIndex, endIndex, sourceTokens, targetTokens, color);
					};
				})	
			});
		}
	}

	function drawLine(source, target, startIndex, endIndex, sourceTokens, targetTokens, color){
		var originX = 0;
		var originY = source.offset().top - $canvas.offset().top + source.height();
		var endingX = $canvas.width();
		var endingY = target.offset().top - $canvas.offset().top + target.height();
		var line = "M" + originX + " " + originY + " L" + endingX + " " + endingY; 
		lines[startIndex][endIndex] = canvas.path(line).attr({
			"stroke": color,
			"stroke-width": 2,
			"stroke-dasharray": "--."
		});	
		if ('green' == color){
			source.addClass('correct');
			target.addClass('correct');
		}		
		if ('orange' == color) {
			source.addClass('wrong');
			target.addClass('wrong');
		};
		source.removeClass('selectedfilter');
	    source.removeClass('ui-selected');
		target.removeClass('selectedfilter');
	    target.removeClass('ui-selected');
	}

	function removeLines(sources, targets) {
		if (sources != [] && targets != []){

			// remove contents from source and target span
			$.each(sources,function(s_i,s_val){
				var $source = $(s_val);
				$($source.children()[1]).text('');
				$($source.children()[2]).text('');
			})
			$.each(targets,function(t_i,t_val){
				var $target = $(t_val);
				$($target.children()[1]).text('');
				$($target.children()[2]).text('');
			})	

			// remove lines
			$.each(sources, function(s_i,s_val){
				var source = $(s_val);
				$.each(targets, function(t_i,t_val){
					var target = $(t_val);
					var startIndex = source.parent().children().index(source);
					var endIndex = target.parent().children().index(target);
					if (lines[startIndex][endIndex] != undefined) {
						lines[startIndex][endIndex].remove();
					};
					source.removeClass('selectedfilter').removeClass('ui-selected');
				    source.removeClass('correct').removeClass('wrong');
					target.removeClass('selectedfilter').removeClass('ui-selected');
				    target.removeClass('correct').removeClass('wrong');
				})	
			});
		}
	}

	$(window).keydown(function(event) {
		var sources = $('#selectable_source .ui-selected');
		var targets = $('#selectable_translation .ui-selected');
		switch(event.keyCode) {
			case KEY.SPACE:
			case KEY.C_SMALL:
			case KEY.C_BIG:
				drawLines(sources, targets, 'green');
				break;
			case KEY.D_SMALL:
			case KEY.D_BIG:
				removeLines(sources, targets);
				break;
			case KEY.I_SMALL:
			case KEY.I_BIG:
				drawLines(sources, targets, 'orange');
				break;
		}
	});

	// $("li").bind('contextmenu',function(event){
	// 	$li = $(event.target);
	// 	$('#menu').css({
	//         top: event.pageY+'px',
	//         left: event.pageX+'px'
	//     }).show();
	// 	return false;
	// });

	// $('#menu').click(function() {
 //        $('#menu').hide();
 //    });
 //    $(document).click(function() {
 //        $('#menu').hide();
 //    });

 //    $("a").bind('click', function(event){
	// 	console.log(this);
	// });

	// $(function(){
	//     $(document).mousedown(function(event){
	//     	$('#menu').hide();
	//     });
	// });

	

	// $("li").mousedown(function(event){
	// 	switch(event.which) {
	//         case MOUSE.RIGHT:
	//             console.log('Right mouse button pressed');
	//             return false;
	//             break;        
	// 	}
	// });

</script>

app/views/welcome/index.html.erb
<% provide :title, "Home" %>
<div class="center hero-unit">
  <h1>Welcome to the Demo App</h1>


  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
</div>